apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: wg-exporter
    app.kubernetes.io/part-of: kilo
  name: wg-exporter
  namespace: kilo
spec:
  namespaceSelector:
    matchNames:
    - kilo
  podMetricsEndpoints:
  - interval: 15s
    path: /metrics
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: wg-exporter
      app.kubernetes.io/part-of: kilo
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: wg-exporter
    app.kubernetes.io/part-of: kilo
  name: wg-exporter
  namespace: kilo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wg-exporter
      app.kubernetes.io/part-of: kilo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wg-exporter
        app.kubernetes.io/part-of: kilo
    spec:
      containers:
      - args:
        - -a=true
        - -i=kilo0
        - -p=9586
        image: mindflavor/prometheus-wireguard-exporter
        name: wg-exporter
        ports:
        - containerPort: 9586
          name: metrics
          protocol: TCP
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/wireguard
          name: wireguard
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /var/run/wireguard
        name: wireguard
