apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: kilo
    app.kubernetes.io/part-of: kilo
  name: kilo
  namespace: kilo
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  podMetricsEndpoints:
  - interval: 15s
    path: /metrics
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/part-of: kilo
