- hosts: tier2hosts
  remote_user: khainguyen
  become_user: khainguyen
  become: true
  gather_facts: true

  vars:
    sinfonia_tier1_url: "http://192.168.245.31:5000"
    sinfonia_tier2_url: "{{ hostvars[inventory_hostname].sinfonia_tier2_url }}"
    sinfonia_tier2_latitude: "{{ hostvars[inventory_hostname].sinfonia_tier2_latitude }}"
    sinfonia_tier2_longitude: "{{ hostvars[inventory_hostname].sinfonia_tier2_longitude }}"
    sinfonia_tier2_zone: "{{ hostvars[inventory_hostname].sinfonia_tier2_zone }}"
    sinfonia_tier3_latitude: "42.340382"
    sinfonia_tier3_longitude: "-72.496819"
    sinfonia_kubeconfig: ""
    sinfonia_kubecontext: ""
    sinfonia_prometheus: "http://kube-prometheus-stack-prometheus.monitoring.svc:9090"
    sinfonia_recipes: "RECIPES"
    enable_ufw: false
    override_resolv_conf: true

  environment:
    SINFONIA_TIER2_LATITUDE: "{{ sinfonia_tier2_latitude }}"
    SINFONIA_TIER2_LONGITUDE: "{{ sinfonia_tier2_longitude }}"
    SINFONIA_TIER3_LATITUDE: "{{ sinfonia_tier3_latitude }}"
    SINFONIA_TIER3_LONGITUDE: "{{ sinfonia_tier3_longitude }}"

  tasks:
  - import_tasks: tasks/latency.yml
