- hosts: tier2hosts
  remote_user: khainguyen
  become_user: root
  become: true
  gather_facts: false

  environment:
    # K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    RAPL_FOLDER: /nfs/obelix/users1/khainguyen/power_data
    OBELIX_NODE_NAME: "{{ inventory_hostname }}"

  tasks:
    - name: kill previous rapl daemons
      ansible.builtin.command:
        cmd: pkill -f "python3 rapl_daemon.py"
      register: command_output
      failed_when: command_output.rc not in [0, 1]

    - name: copy rapl daemon script
      ansible.builtin.copy:
        src: scripts/rapl_daemon.py
        dest: ./rapl_daemon.py
        mode: '0755'

    - name: install dependencies
      ansible.builtin.pip:
        executable: pip3
        name: git+https://github.com/wkatsak/py-rapl
        state: present

    - name: start rapl daemons
      shell: nohup python3 rapl_daemon.py &
      # async: 0
      # poll: 0
