logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    default:
      "()": src.domain.logger.formatter.DefaultFormatter
  handlers:
    console:
      level: INFO
      formatter: default
      class: logging.StreamHandler
      stream: ext://sys.stdout
  root:
    handlers: [console]
    level: DEBUG

tier1:
  timeout_seconds: 15
  port: 5000
  root_url: http://localhost
  api_path: api/v1

tier2:
  timeout_seconds: 15
  port: 30051
  root_url: http://192.168.245.32
  api_path: api/v1
  # port: 80
  # root_url: http://10.43.223.99
