logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    default:
      "()": src.domain.logger.formatter.DefaultFormatter
  handlers:
    console:
      level: INFO
      formatter: default
      class: logging.StreamHandler
      stream: ext://sys.stdout
  root:
    handlers: [console]
    level: INFO

tier1:
  timeout_seconds: 8
  port: 5000
  root_url: http://localhost
  api_path: api/v1

tier2:
  timeout_seconds: 8
  port: 80
  root_url: http://10.43.198.193
  api_path: api/v1
