# SPDX-FileCopyrightText: 2022 Carnegie Mellon University
# SPDX-License-Identifier: 0BSD

helmDefaults:
  atomic: true
  wait: true

releases:
- name: sinfonia-tier1
  namespace: findcloudlet
  createNamespace: true
  chart: ../charts/sinfonia
  installed: true
  values:
    - sinfoniaTier1: true
      ingress:
        annotations:
            kubernetes.io/ingress-class: "nginx"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: '{{ requiredEnv "SINFONIA_TIER1_FQDN" }}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: sinfonia-tier1-cert
            hosts:
              - '{{ requiredEnv "SINFONIA_TIER1_FQDN" }}'
