apiVersion: v1
kind: Service
metadata:
  name: {{ template "openrtist.name" . }}
  labels:
    {{- include "openrtist.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: openrtist
      protocol: TCP
      name: openrtist
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "openrtist.selectorLabels" . | nindent 4 }}
