- name: copy latency script
  ansible.builtin.copy:
    src: latency.py
    dest: ./latency.py
    mode: '0755'

- name: set latency simulation for tier2 services
  ansible.builtin.command:
    cmd: python3 latency.py
